server:
    port: 8080
    servlet:
        encoding:
            charset: UTF-8
            force: true
            enabled: true
spring:
    profiles:
        active: discovery, local         #discovery는 필수, 나머지는 상황에 따라..
    main:
        allow-circular-references: true

ENV:
    SPRING_MAIL_HOST: smtp.gmail.com
    SPRING_MAIL_PORT: 587
    SPRING_MAIL_USERNAME: skylab@mercuryproject.com
    SPRING_MAIL_PASSWORD: MPDev123!

    DATASOURCE_DIALECT: mysql       #mysql, oracle
    DATASOURCE_DRIVER_CLASS_NAME: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    DATASOURCE_JDBC_URL: jdbc:log4jdbc:mysql://34.64.204.168:3306/LittleJoe_Dev2?allowMultiQueries=true
    DATASOURCE_USER_NAME: mp_admin
    DATASOURCE_USER_PASSWORD: 1q2w3e4r%T
    DATASOURCE_POOL_SIZE: 5

    REDIS_HOST: 34.64.204.168
    REDIS_PORT: 6001
    REDIS_PASSWORD:

    APPS_REQUEST_MAPPING: /api/v2
    APPS_HOST: http://localhost:${server.port}
    APPS_MODE: on-premise

    APPS_ENCRYPTION_KEY: ENC(Hkolyo7gXulS+kALO5yRUAdmjp+BaZG1KIHCldKDvy0=)

    # 서버 응답 압축관련
    SERVER_COMPRESSION_ENABLED: false
    SERVER_COMPRESSION_MIMETYPES: application/json,application/javascript
    SERVER_COMPRESSION_MINSIZE: 1024

ubicus:
    sitemenu:
        controller:
            mapping: /base/menu
            index: base/menu/index
        #type: dbms
        #source: dure
        #tableName: tb_cmm_sitemenu
        type: xml
        source: classpath:sitemenu.xml
        autoReloadIntervalSec: 60
        urlMethods: GET,POST,PUT,PATCH,DELETE
        urlPattern:
            - /*
        templates:
            - front:프론트:/WEB-INF/templates/sitemenu/front/template.jsp
        roles:
            USER: 사용자
            EDITOR: 에디터
            ADMIN: 관리자


---
spring:
    config:
        activate:
            on-profile: local
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
